import { describe, expect, it, vi } from "vitest";
import type { StatementExportDocument } from "../model";
import {
  exportStatementMarkdown,
  formatMarkdownAmount,
  statementToMarkdown,
  type StatementTranslator,
} from "../markdown";

const { downloadText } = vi.hoisted(() => ({ downloadText: vi.fn() }));
vi.mock("@/common/lib/export/text", () => ({ downloadText }));

const messages: Record<string, string> = {
  "common.accountColumn": "Account",
  "component.conversionSelect.atCost": "At cost",
  "component.conversionSelect.atMarketValue": "At market value",
  "component.conversionSelect.units": "Units",
  "component.conversionSelect.convertedTo": "Converted to",
  "reports.export.accountFilter": "Account filter",
  "reports.export.advancedFilter": "Advanced filter",
  "reports.export.allActivity": "All available ledger activity through",
  "reports.export.amount": "Amount",
  "reports.export.asOf": "As of",
  "reports.export.asOfDateUnavailableNotice":
    "An as-of date could not be determined. This statement remains an internal draft.",
  "reports.export.balanceSheetClassificationNotice":
    "Current and non-current classifications are not available from the source ledger; accounts are presented in ledger order.",
  "reports.export.balanceSheetDoesNotReconcileNotice":
    "The accounting equation does not reconcile for one or more units. This statement remains an internal draft.",
  "reports.export.context": "Scope and basis",
  "reports.export.conversion": "Conversion",
  "reports.export.customUnitsDefinitionNotice":
    "Their meanings are not available in this export; document them in an accompanying note before external use.",
  "reports.export.customUnitsNotice": "Custom ledger units requiring review:",
  "reports.export.dateUnavailable": "Reporting date unavailable",
  "reports.export.generatedBy": "Generated by Beancount.io on {generatedAt}",
  "reports.export.importantNotices": "Important notices",
  "reports.export.inferredPeriodNotice":
    "This report covers ledger activity from {startDate} through {endDate}. The dates were derived from the available report data.",
  "reports.export.inferredAsOfDateNotice":
    "No explicit as-of date was selected. This statement uses the latest date available in the report: {asOfDate}.",
  "reports.export.ledgerUnits": "Ledger units shown",
  "reports.export.lineItem": "Line item",
  "reports.export.multiUnitScheduleNotice":
    "This multi-unit report is a management schedule, not a single-currency financial statement. Do not add amounts across units; select a presentation currency before external use.",
  "reports.export.netIncome": "Net Income",
  "reports.export.netLoss": "Net Loss",
  "reports.export.noAssurance": "No assurance is provided.",
  "reports.export.partialReportNotice": "This is a partial statement.",
  "reports.export.period": "For the period",
  "reports.export.periodNotExplicitNotice":
    "A complete reporting period could not be determined. This statement remains an internal draft.",
  "reports.export.placeholderDataNotice":
    "The reporting identity appears to contain example data.",
  "reports.export.presentationCurrency": "Presentation currency",
  "reports.export.reportingEntity": "Reporting entity",
  "reports.export.reportingEntityFallbackNotice":
    "No reporting entity is configured.",
  "reports.export.sourceLedger": "Source ledger",
  "reports.export.statementSummary": "Statement summary",
  "reports.export.subtotalRowsNotice":
    "Bold rows are subtotals or totals and should not be added to their underlying detail rows.",
  "reports.export.supportingAccountDetail": "Supporting Account Detail",
  "reports.export.totalAssets": "Total Assets",
  "reports.export.totalEquity": "Total Equity",
  "reports.export.totalExpenses": "Total Expenses",
  "reports.export.totalLiabilities": "Total Liabilities",
  "reports.export.totalLiabilitiesAndEquity": "Total Liabilities and Equity",
  "reports.export.totalRevenue": "Total Revenue and Other Income",
  "reports.export.reconciliationDifference": "Reconciliation Difference",
  "reports.export.unauditedInternalDraft": "Unaudited internal draft",
  "reports.export.unauditedManagementReport": "Unaudited management report",
  "reports.export.unauditedMultiUnitManagementReport":
    "Unaudited multi-unit management schedule",
  "reports.export.unit": "Unit",
};

const t: StatementTranslator = (key, params) => {
  return Object.entries(params ?? {}).reduce(
    (message, [name, value]) => message.replaceAll(`{${name}}`, value),
    messages[key] ?? key,
  );
};

function fixture(): StatementExportDocument {
  return {
    kind: "profit_and_loss",
    title: "Income Statement",
    context: {
      reportingEntity: "Northstar Household",
      reportingEntitySource: "ledger_title",
      ledgerName: "northstar-books",
      primaryCurrency: "USD",
      conversion: "USD",
      interval: "monthly",
      filters: { time: "", account: "", filter: "" },
      reportingPeriod: {
        startDate: "2023-01-01",
        endDate: "2025-10-31",
        asOfDate: null,
        isExplicit: false,
        selection: "",
      },
      generatedAt: "2026-08-16T12:00:00.000Z",
    },
    sections: [
      {
        key: "income",
        label: "Income",
        rows: [
          {
            accountPath: "Income",
            label: "Income",
            depth: 0,
            rowKind: "total",
            amounts: [
              {
                unit: "USD",
                rawAmount: "-367048.43",
                displayAmount: "367048.43",
              },
              {
                unit: "IRAUSD",
                rawAmount: "-55500",
                displayAmount: "55500",
              },
              {
                unit: "VACHR",
                rawAmount: "-365",
                displayAmount: "365",
              },
            ],
          },
          {
            accountPath: "Income:Salary",
            label: "Salary",
            depth: 1,
            rowKind: "account",
            amounts: [
              {
                unit: "USD",
                rawAmount: "-311548.43",
                displayAmount: "311548.43",
              },
            ],
          },
          {
            accountPath: "Income:Other",
            label: "Other",
            depth: 1,
            rowKind: "account",
            amounts: [
              { unit: "USD", rawAmount: "-55500", displayAmount: "55500" },
              {
                unit: "IRAUSD",
                rawAmount: "-55500",
                displayAmount: "55500",
              },
              { unit: "VACHR", rawAmount: "-365", displayAmount: "365" },
            ],
          },
        ],
      },
      {
        key: "expenses",
        label: "Expenses",
        rows: [
          {
            accountPath: "Expenses",
            label: "Expenses",
            depth: 0,
            rowKind: "total",
            amounts: [
              {
                unit: "USD",
                rawAmount: "263090.25",
                displayAmount: "263090.25",
              },
              {
                unit: "IRAUSD",
                rawAmount: "55500",
                displayAmount: "55500",
              },
              { unit: "VACHR", rawAmount: "480", displayAmount: "480" },
            ],
          },
          {
            accountPath: "Expenses:Living",
            label: "Living",
            depth: 1,
            rowKind: "account",
            amounts: [
              {
                unit: "USD",
                rawAmount: "262725.25",
                displayAmount: "262725.25",
              },
            ],
          },
          {
            accountPath: "Expenses:Fees",
            label: "Fees",
            depth: 1,
            rowKind: "account",
            amounts: [
              { unit: "USD", rawAmount: "365", displayAmount: "365" },
              {
                unit: "IRAUSD",
                rawAmount: "55500",
                displayAmount: "55500",
              },
              { unit: "VACHR", rawAmount: "480", displayAmount: "480" },
            ],
          },
        ],
      },
      {
        key: "net_profit",
        label: "Net Income",
        rows: [
          {
            accountPath: "Net Income",
            label: "Net Income",
            depth: 0,
            rowKind: "total",
            amounts: [
              {
                unit: "USD",
                rawAmount: "-103958.18",
                displayAmount: "103958.18",
              },
              { unit: "IRAUSD", rawAmount: "0", displayAmount: "0" },
              { unit: "VACHR", rawAmount: "115", displayAmount: "-115" },
            ],
          },
        ],
      },
    ],
  };
}

function balanceSheetFixture(): StatementExportDocument {
  const base = fixture();
  const amount = (value: string, inverted = false) => ({
    unit: "USD",
    rawAmount: inverted ? `-${value}` : value,
    displayAmount: value,
  });

  return {
    ...base,
    kind: "balance_sheet",
    title: "Balance Sheet",
    context: {
      ...base.context,
      filters: { time: "2025", account: "", filter: "" },
      reportingPeriod: {
        startDate: null,
        endDate: null,
        asOfDate: "2025-12-31",
        isExplicit: true,
        selection: "2025",
      },
    },
    sections: [
      {
        key: "assets",
        label: "Assets",
        rows: [
          {
            accountPath: "Assets",
            label: "Assets",
            depth: 0,
            rowKind: "total",
            amounts: [amount("425000")],
          },
          {
            accountPath: "Assets:Cash",
            label: "Cash",
            depth: 1,
            rowKind: "account",
            amounts: [amount("425000")],
          },
        ],
      },
      {
        key: "liabilities",
        label: "Liabilities",
        rows: [
          {
            accountPath: "Liabilities",
            label: "Liabilities",
            depth: 0,
            rowKind: "total",
            amounts: [amount("121000", true)],
          },
          {
            accountPath: "Liabilities:Loans",
            label: "Loans",
            depth: 1,
            rowKind: "account",
            amounts: [amount("121000", true)],
          },
        ],
      },
      {
        key: "equity",
        label: "Equity",
        rows: [
          {
            accountPath: "Equity",
            label: "Equity",
            depth: 0,
            rowKind: "total",
            amounts: [amount("304000", true)],
          },
          {
            accountPath: "Equity:Opening-Balances",
            label: "Opening-Balances",
            depth: 1,
            rowKind: "account",
            amounts: [amount("304000", true)],
          },
        ],
      },
    ],
  };
}

describe("statement Markdown", () => {
  it("formats exact decimals consistently without losing extra precision", () => {
    expect(formatMarkdownAmount("55500", "en-US")).toBe("55,500.00");
    expect(formatMarkdownAmount("365", "en-US")).toBe("365.00");
    expect(formatMarkdownAmount("-12.3456", "en-US")).toBe("(12.3456)");
    expect(formatMarkdownAmount("9007199254740993.2", "en-US")).toBe(
      "9,007,199,254,740,993.20",
    );
  });

  it("separates a multi-unit statement summary from supporting detail", () => {
    const markdown = statementToMarkdown(fixture(), { locale: "en-US", t });

    expect(markdown).toContain("# Northstar Household");
    expect(markdown).toContain("## Income Statement");
    expect(markdown).toContain(
      "**For the period January 1, 2023 – October 31, 2025**",
    );
    expect(markdown).toContain(
      "This report covers ledger activity from January 1, 2023 through October 31, 2025. The dates were derived from the available report data.",
    );
    expect(markdown).not.toContain("No explicit reporting period was selected");
    expect(markdown).toContain(
      "***Unaudited multi-unit management schedule***",
    );
    expect(markdown).toContain(
      "This multi-unit report is a management schedule, not a single-currency financial statement. Do not add amounts across units; select a presentation currency before external use.",
    );
    expect(markdown).toContain("## Statement summary");
    expect(markdown).toContain("| Line item | Unit | Amount |");
    expect(markdown).toContain(
      "| **Total Revenue and Other Income** | **USD** | **367,048.43** |",
    );
    expect(markdown).toContain(
      "| **Total Expenses** | **USD** | **263,090.25** |",
    );
    expect(markdown).toContain("| Income:Other | USD | 55,500.00 |");
    expect(markdown).toContain("| Expenses:Fees | USD | 365.00 |");
    expect(markdown).toContain("| **Net Income** | **USD** | **103,958.18** |");
    expect(markdown).toContain("| **Net Income** | **IRAUSD** | **0.00** |");
    expect(markdown).toContain("| **Net Loss** | **VACHR** | **(115.00)** |");
    expect(markdown).toContain("## Supporting Account Detail");
    expect(markdown).toContain("### Income");
    expect(markdown).toContain("### Expenses");
    expect(markdown).not.toContain("| **Income** | **USD** | **367,048.43** |");
    expect(markdown).not.toContain("Net Profit");
    expect(markdown).toContain(
      "Bold rows are subtotals or totals and should not be added to their underlying detail rows.",
    );
    expect(markdown).toContain(
      "Custom ledger units requiring review: IRAUSD, VACHR. Their meanings are not available in this export; document them in an accompanying note before external use.",
    );
    expect(markdown).toContain("No assurance is provided.");
  });

  it("uses formal single-currency labeling when all rows use USD", () => {
    const document = fixture();
    document.sections.forEach((section) =>
      section.rows.forEach((row) => {
        row.amounts = row.amounts.filter((amount) => amount.unit === "USD");
      }),
    );

    const markdown = statementToMarkdown(document, { locale: "en-US", t });

    expect(markdown).toContain("***Unaudited management report***");
    expect(markdown).toContain("**Presentation currency:** USD");
    expect(markdown).not.toContain("multi-unit management schedule");
    expect(markdown).not.toContain(
      "Do not add amounts across units; select a presentation currency",
    );
  });

  it("renders a balanced balance-sheet summary before supporting detail", () => {
    const markdown = statementToMarkdown(balanceSheetFixture(), {
      locale: "en-US",
      t,
    });

    expect(markdown).toContain("## Balance Sheet");
    expect(markdown).toContain("**As of December 31, 2025**");
    expect(markdown).toContain("***Unaudited management report***");
    expect(markdown).toContain("**Presentation currency:** USD");
    expect(markdown).toContain("## Statement summary");
    expect(markdown).toContain(
      "| **Total Assets** | **USD** | **425,000.00** |",
    );
    expect(markdown).toContain(
      "| **Total Liabilities** | **USD** | **121,000.00** |",
    );
    expect(markdown).toContain(
      "| **Total Equity** | **USD** | **304,000.00** |",
    );
    expect(markdown).toContain(
      "| **Total Liabilities and Equity** | **USD** | **425,000.00** |",
    );
    expect(markdown).toContain(
      "| **Reconciliation Difference** | **USD** | **0.00** |",
    );
    expect(markdown).toContain(
      "Current and non-current classifications are not available from the source ledger; accounts are presented in ledger order.",
    );
    expect(markdown).toContain("## Supporting Account Detail");
    expect(markdown.indexOf("## Statement summary")).toBeLessThan(
      markdown.indexOf("## Supporting Account Detail"),
    );
    expect(markdown).toContain("| Assets:Cash | USD | 425,000.00 |");
    expect(markdown).toContain(
      "| **Total Assets** | **USD** | **425,000.00** |",
    );
    expect(markdown).not.toContain("| **Assets** | **USD**");
  });

  it("marks a non-reconciling balance sheet as an internal draft", () => {
    const document = balanceSheetFixture();
    document.sections[2].rows.forEach((row) => {
      row.amounts[0] = {
        unit: "USD",
        rawAmount: "-300000",
        displayAmount: "300000",
      };
    });

    const markdown = statementToMarkdown(document, { locale: "en-US", t });

    expect(markdown).toContain("***Unaudited internal draft***");
    expect(markdown).toContain(
      "| **Reconciliation Difference** | **USD** | **4,000.00** |",
    );
    expect(markdown).toContain(
      "The accounting equation does not reconcile for one or more units. This statement remains an internal draft.",
    );
  });

  it("labels a multi-unit balance sheet as a management schedule", () => {
    const document = balanceSheetFixture();
    const amounts = ["100", "40", "60"];
    document.sections.forEach((section, sectionIndex) => {
      section.rows.forEach((row) => {
        const displayAmount = amounts[sectionIndex];
        row.amounts.push({
          unit: "EUR",
          rawAmount:
            section.key === "assets" ? displayAmount : `-${displayAmount}`,
          displayAmount,
        });
      });
    });

    const markdown = statementToMarkdown(document, { locale: "en-US", t });

    expect(markdown).toContain(
      "***Unaudited multi-unit management schedule***",
    );
    expect(markdown).toContain(
      "This multi-unit report is a management schedule, not a single-currency financial statement.",
    );
    expect(markdown).toContain(
      "| **Total Liabilities and Equity** | **EUR** | **100.00** |",
    );
    expect(markdown).toContain(
      "| **Reconciliation Difference** | **EUR** | **0.00** |",
    );
  });

  it("describes an inferred balance-sheet date without using period wording", () => {
    const document = balanceSheetFixture();
    document.context.reportingPeriod.isExplicit = false;
    document.context.reportingPeriod.selection = "";

    const markdown = statementToMarkdown(document, { locale: "en-US", t });

    expect(markdown).toContain(
      "No explicit as-of date was selected. This statement uses the latest date available in the report: December 31, 2025.",
    );
    expect(markdown).not.toContain(
      "A complete reporting period could not be determined",
    );
  });

  it("flags obvious example identities instead of silently presenting them", () => {
    const document = fixture();
    document.context.reportingEntity = "Example Beancount file";
    document.context.ledgerName = "Hooli";

    expect(statementToMarkdown(document, { locale: "en-US", t })).toContain(
      "The reporting identity appears to contain example data.",
    );

    document.context.reportingEntity = "Northstar Household";
    document.context.ledgerName = "my-book";
    expect(statementToMarkdown(document, { locale: "en-US", t })).toContain(
      "The reporting identity appears to contain example data.",
    );
  });

  it("keeps the draft warning when the complete period cannot be determined", () => {
    const document = fixture();
    document.context.reportingPeriod.startDate = null;

    expect(statementToMarkdown(document, { locale: "en-US", t })).toContain(
      "A complete reporting period could not be determined. This statement remains an internal draft.",
    );
  });

  it("downloads the reviewed content as a Markdown file", () => {
    const document = fixture();
    const markdown = exportStatementMarkdown(document, {
      locale: "en-US",
      t,
    });

    expect(downloadText).toHaveBeenCalledWith(
      markdown,
      "Northstar-Household-profit_and_loss-2023-01-01-to-2025-10-31-USD-2026-08-16.md",
      "text/markdown;charset=utf-8",
    );
  });
});
