import { entryInputToText } from "@/foundation/rustledger/entry-build";
import type { LedgerEntryInput } from "@/foundation/ledger-api-types/ledger-entry-input";
import golden from "./entry-build.golden.json";

/**
 * GOLDEN parity test. `entry-build.golden.json` is captured verbatim from the
 * real Python `fava.file.format_entries([create.<directive>(...)])` (the path
 * `server/app/api/entries.py::add_bulk_entries` uses to serialize each entry),
 * generated by feeding the same directive payloads through the in-repo
 * fava-slim + beancount venv. Each case asserts `entryInputToText` is
 * byte-identical to what Python emits for that single directive.
 */

const goldenText: Record<string, string> = golden;

/** One golden key → the structured input that must serialize to it. */
const cases: Array<{ name: string; input: LedgerEntryInput }> = [
  {
    name: "transaction_full",
    input: {
      type: "transaction",
      entry: {
        date: "2024-01-15",
        flag: "*",
        payee: "Employer",
        narration: "Salary",
        tags: ["income"],
        links: ["ref-1"],
        postings: [
          {
            units: { number: "3000.00", currency: "USD" },
            account: "Assets:Checking",
          },
          {
            units: { number: "-3000.00", currency: "USD" },
            account: "Income:Salary",
          },
        ],
      },
    },
  },
  {
    name: "transaction_narration_only",
    input: {
      type: "transaction",
      entry: {
        date: "2024-01-20",
        flag: "*",
        narration: "Groceries",
        postings: [
          {
            units: { number: "-50.00", currency: "USD" },
            account: "Assets:Checking",
          },
          {
            units: { number: "50.00", currency: "USD" },
            account: "Expenses:Food",
          },
        ],
      },
    },
  },
  {
    name: "transaction_payee_only_pending",
    input: {
      type: "transaction",
      entry: {
        date: "2024-02-01",
        flag: "!",
        payee: "Store",
        postings: [
          {
            units: { number: "-10.00", currency: "USD" },
            account: "Assets:Cash",
          },
          {
            units: { number: "10.00", currency: "USD" },
            account: "Expenses:Misc",
          },
        ],
      },
    },
  },
  {
    name: "transaction_price_flag_meta",
    input: {
      type: "transaction",
      entry: {
        date: "2024-03-01",
        flag: "*",
        narration: "FX trade",
        meta: { key1: "value1", num: "note" },
        postings: [
          {
            units: { number: "100.00", currency: "USD" },
            account: "Assets:USD",
            price: { number: "1.35", currency: "CAD" },
            flag: "!",
          },
          {
            units: { number: "-135.00", currency: "CAD" },
            account: "Assets:CAD",
          },
        ],
      },
    },
  },
  {
    name: "transaction_escaping",
    input: {
      type: "transaction",
      entry: {
        date: "2024-04-01",
        flag: "*",
        payee: 'Quote"Co',
        narration: "Line\\back",
        postings: [
          {
            units: { number: "-5.00", currency: "USD" },
            account: "Assets:Cash",
          },
          { units: { number: "5.00", currency: "USD" }, account: "Expenses:X" },
        ],
      },
    },
  },
  {
    name: "commodity",
    input: {
      type: "commodity",
      entry: { date: "2024-01-01", currency: "USD" },
    },
  },
  {
    name: "price",
    input: {
      type: "price",
      entry: {
        date: "2024-01-01",
        currency: "AAPL",
        amount: { number: "150.25", currency: "USD" },
      },
    },
  },
  {
    name: "note",
    input: {
      type: "note",
      entry: {
        date: "2024-01-01",
        content: "hello world",
        account: "Assets:Cash",
      },
    },
  },
  {
    name: "balance",
    input: {
      type: "balance",
      entry: {
        date: "2024-01-01",
        account: "Assets:Checking",
        amount: { number: "1000.00", currency: "USD" },
      },
    },
  },
  {
    name: "open_multi",
    input: {
      type: "open",
      entry: {
        date: "2024-01-01",
        account: "Assets:Checking",
        currencies: ["USD", "EUR"],
      },
    },
  },
  {
    name: "open_none",
    input: {
      type: "open",
      entry: { date: "2024-01-01", account: "Assets:Checking", currencies: [] },
    },
  },
  {
    name: "close",
    input: {
      type: "close",
      entry: { date: "2024-01-01", account: "Assets:Checking" },
    },
  },
  {
    name: "event",
    input: {
      type: "event",
      entry: {
        date: "2024-01-01",
        type: "location",
        description: "Paris, France",
      },
    },
  },
  {
    name: "document",
    input: {
      type: "document",
      entry: {
        date: "2024-01-01",
        account: "Assets:Cash",
        filename: "/path/to/doc.pdf",
      },
    },
  },
  {
    name: "document_tags_links",
    input: {
      type: "document",
      entry: {
        date: "2024-01-01",
        account: "Assets:Cash",
        filename: "/path/to/doc.pdf",
        tags: ["tagb", "taga"],
        links: ["link1"],
      },
    },
  },
  {
    name: "budget",
    input: {
      type: "budget",
      entry: {
        date: "2024-01-01",
        account: "Expenses:Food",
        interval: "monthly",
        amount: { number: "500.00", currency: "USD" },
      },
    },
  },
];

describe("entryInputToText — Fava-exact serialization parity", () => {
  it.each(cases)(
    "matches Python format_entries for $name",
    ({ name, input }) => {
      expect(goldenText[name]).toBeDefined();
      expect(entryInputToText(input)).toBe(goldenText[name]);
    },
  );

  it("covers every golden fixture", () => {
    const covered = new Set(cases.map((testCase) => testCase.name));
    const goldenKeys = Object.keys(goldenText);
    expect(goldenKeys.every((key) => covered.has(key))).toBe(true);
    expect(covered.size).toBe(goldenKeys.length);
  });

  /**
   * A budget reaches this module as a `custom` directive, because that is the
   * only shape the bulk-entries contract defines for one — there is no
   * `budget` entry type on the wire (`EntryAddBulkEntriesRequest` in
   * `idl/beancount-ledger.openapi.json`). This module used to handle only the
   * in-process `budget` union, so every budget written through the API failed
   * with "Cannot read properties of undefined (reading 'type')".
   */
  it("renders a wire-shaped custom budget identically to the budget input", () => {
    const fromWire = entryInputToText({
      type: "custom",
      entry: {
        date: "2024-01-01",
        type: "budget",
        values: [
          { kind: "account", value: "Expenses:Food" },
          { kind: "text", value: "monthly" },
          { kind: "amount", number: "500.00", currency: "USD" },
        ],
      },
    });

    expect(fromWire).toBe(goldenText.budget);
  });

  it("maps every custom value kind onto its beancount rendering", () => {
    // `text` quotes, `account` does not, `number` is bare, `amount` pairs
    // number and currency — the four kinds the contract defines.
    const out = entryInputToText({
      type: "custom",
      entry: {
        date: "2024-03-04",
        type: "example",
        values: [
          { kind: "account", value: "Assets:Checking" },
          { kind: "text", value: "quoted" },
          { kind: "number", value: "12.50" },
          { kind: "amount", number: "3.00", currency: "EUR" },
        ],
      },
    });

    expect(out).toBe(
      '2024-03-04 custom "example" Assets:Checking "quoted" 12.50 3.00 EUR\n\n',
    );
  });

  it("renders a custom directive that carries no values", () => {
    expect(
      entryInputToText({
        type: "custom",
        entry: { date: "2024-03-04", type: "marker" },
      }),
    ).toBe('2024-03-04 custom "marker"\n\n');
  });

  it("appends the trailing blank line that format_entries adds", () => {
    const out = entryInputToText({
      type: "close",
      entry: { date: "2024-01-01", account: "Assets:Checking" },
    });
    expect(out.endsWith("\n\n")).toBe(true);
  });

  it("round-trips tags/links sorted regardless of input order", () => {
    const out = entryInputToText({
      type: "document",
      entry: {
        date: "2024-01-01",
        account: "Assets:Cash",
        filename: "/path/to/doc.pdf",
        tags: ["zeta", "alpha"],
        links: ["mno"],
      },
    });
    expect(out).toContain("#alpha#zeta^mno");
  });
});
