#!/usr/bin/env python3
"""Generate `docs/REFERENCE.md` from the registered Typer command tree.

The tree is the source of truth for what a command accepts: the usage line,
arguments, and options (name, type, default, help) for every leaf, grouped by
the top-level help panels. Run through `make docs`; the output is committed
and `make docs-check` (in `make check-all`) fails when it is stale, so help
text cannot drift from the reference. Do not hand-edit the output.

Tree handles are typed `Any` deliberately: Typer resolves the app against its
vendored click, whose classes differ from the top-level `click` package, so
only duck-typed access (`list_commands`, `params`, `opts`, ...) is portable.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from enum import Enum
from pathlib import Path
from typing import Any

import click
import typer.main

CLI_DIR = Path(__file__).resolve().parent.parent
REFERENCE = CLI_DIR / "docs" / "REFERENCE.md"


def walk(root: Any) -> tuple[list[Any], list[tuple[str, str, Any, Any]]]:
    """Root globals plus `(panel, path, leaf, context)` for every visible leaf."""
    leaves: list[tuple[str, str, Any, Any]] = []
    root_ctx = click.Context(root, info_name="bea")

    def visit(command: Any, path: list[str], ctx: Any, panel: str | None) -> None:
        if command is None or getattr(command, "hidden", False):
            return
        panel = panel or getattr(command, "rich_help_panel", None)
        subcommands: list[tuple[str, Any]] = []
        if callable(getattr(command, "list_commands", None)):
            for name in command.list_commands(ctx):
                sub = command.get_command(ctx, name)
                if sub is not None:
                    subcommands.append((name, sub))
        if subcommands:
            for name, sub in subcommands:
                visit(sub, [*path, name], click.Context(sub, info_name=name, parent=ctx), panel)
        else:
            leaves.append((panel or "Commands", " ".join(path), command, ctx))

    visit(root, ["bea"], root_ctx, None)
    return list(root.params), leaves


def cell(value: object) -> str:
    """One Markdown table cell: no newlines, no raw pipes."""
    return " ".join(str(value).split()).replace("|", "\\|")


def type_label(param: Any) -> str:
    kind = getattr(param, "param_type_name", "")
    param_type = getattr(param, "type", None)
    name = getattr(param_type, "name", None) or type(param_type).__name__
    if name == "choice":
        choices = getattr(param_type, "choices", None)
        if choices is not None:
            return "choice: " + " | ".join(str(choice) for choice in choices)
        return name
    if kind == "option" and getattr(param, "is_bool_flag", False):
        return "flag"
    label = name
    if getattr(param, "multiple", False):
        label += " (repeatable)"
    return label


def default_label(param: Any) -> str:
    if getattr(param, "required", False):
        return "required"
    default = getattr(param, "default", None)
    if default is None or default is False:
        return ""
    if default is True:
        return "True"
    if isinstance(default, Enum):
        return str(default.value)
    if isinstance(default, (list, tuple)):
        return ", ".join(str(item) for item in default)
    return str(default)


def option_names(param: Any) -> str:
    return ", ".join([*getattr(param, "opts", []), *getattr(param, "secondary_opts", [])])


def help_of(param: Any) -> str:
    return cell(getattr(param, "help", "") or "")


def options_table(params: list[Any]) -> list[str]:
    lines = ["| Option | Type | Default | Help |", "| --- | --- | --- | --- |"]
    for param in params:
        lines.append(
            f"| `{cell(option_names(param))}` | {cell(type_label(param))} "
            f"| {cell(default_label(param))} | {help_of(param)} |"
        )
    return lines


def render() -> str:
    from cli.config import package_version
    from cli.main import app

    root = typer.main.get_command(app)
    globals_, leaves = walk(root)
    version = package_version()
    lines = [
        "# `bea` command reference",
        "",
        f"> Generated by `scripts/gen_reference.py` from bea {version} — do not hand-edit; run `make docs`.",
        "",
        "Global options apply to every command. Each section below lists one leaf command",
        "with its usage line, arguments, and options.",
        "",
        "## Global options",
        "",
        *options_table(globals_),
        "",
    ]
    for panel in dict.fromkeys(panel for panel, _path, _leaf, _ctx in leaves):
        lines += [f"## {panel}", ""]
        for leaf_panel, path, leaf, ctx in leaves:
            if leaf_panel != panel:
                continue
            short_help = (getattr(leaf, "help", None) or "").strip().splitlines()
            lines += [f"### `{path}`", ""]
            if short_help:
                lines += [short_help[0], ""]
            lines += ["```text", f"Usage: {path} {' '.join(leaf.collect_usage_pieces(ctx))}".rstrip(), "```"]
            arguments = [p for p in leaf.params if getattr(p, "param_type_name", "") == "argument"]
            options = [p for p in leaf.params if getattr(p, "param_type_name", "") == "option"]
            if arguments:
                lines += [
                    "",
                    "| Argument | Type | Required | Help |",
                    "| --- | --- | --- | --- |",
                ]
                for param in arguments:
                    required = "yes" if getattr(param, "required", False) else "no"
                    lines.append(
                        f"| `{cell(getattr(param, 'name', ''))}` | {cell(type_label(param))} "
                        f"| {required} | {help_of(param)} |"
                    )
            if options:
                lines += ["", *options_table(options)]
            if leaf.epilog:
                lines += ["", "```text", leaf.epilog.replace("\b\n", ""), "```"]
            lines += [""]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/REFERENCE.md from the command tree.")
    parser.add_argument("--check", action="store_true", help="Diff against the committed file instead of writing")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        if REFERENCE.is_file() and REFERENCE.read_text() == text:
            return 0
        expected = REFERENCE.read_text().splitlines() if REFERENCE.is_file() else []
        diff = "\n".join(difflib.unified_diff(expected, text.splitlines(), "docs/REFERENCE.md", "regenerated"))
        print(f"docs/REFERENCE.md is stale — run 'make docs' and commit the diff:\n{diff}")
        return 1
    REFERENCE.write_text(text)
    print(f"Wrote {REFERENCE} ({len(text.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
