#!/usr/bin/env bash
# Render the Homebrew formula for a published beancount-io release to stdout.
#
#   bash scripts/render-formula.sh <version> <sdist-sha256> > bea.rb
#
# The formula is thin on purpose: PyPI is the single release source, and the
# only thing Homebrew adds is a managed virtualenv. Dependencies come from the
# `requirements.lock` the sdist carries — a full hash-pinned export of the same
# resolution CI tested — so an install resolves nothing and compiles nothing.
set -euo pipefail

version="${1:?usage: render-formula.sh <version> <sdist-sha256>}"
sha256="${2:?usage: render-formula.sh <version> <sdist-sha256>}"

# Both values are interpolated into Ruby source and a URL. They are validated
# up front, and nothing is printed until they pass, so a bad input can never
# leave a half-rendered formula on the tap.
if [[ ! "$version" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
  echo "error: version '$version' is not a canonical X.Y.Z" >&2
  exit 1
fi
if [[ ! "$sha256" =~ ^[0-9a-f]{64}$ ]]; then
  echo "error: '$sha256' is not a lowercase hex sha256" >&2
  exit 1
fi

cat <<EOF
# Generated by cli/scripts/render-formula.sh for cli-v${version} — do not edit.
class Bea < Formula
  desc "Beancount.io CLI: check, query, report on, and edit beancount ledgers"
  homepage "https://beancount.io"
  url "https://files.pythonhosted.org/packages/source/b/beancount-io/beancount_io-${version}.tar.gz"
  sha256 "${sha256}"
  license "MIT"

  depends_on "python@3.12"
  depends_on "uv" => :build

  def install
    python = Formula["python@3.12"].opt_bin/"python3.12"
    system "uv", "venv", "--python", python, libexec
    # --require-hashes: every dependency is pinned to the exact artifact CI
    # tested, so no version resolution and no source build happen on a user's
    # machine (pydantic-core in particular must arrive as a wheel).
    system "uv", "pip", "install", "--python", libexec/"bin/python",
           "--require-hashes", "--requirement", "requirements.lock"
    system "uv", "pip", "install", "--python", libexec/"bin/python", "--no-deps", "."
    bin.install_symlink libexec/"bin/bea"
  end

  test do
    assert_match "bea #{version}", shell_output("#{bin}/bea --version")
  end
end
EOF
