# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Any, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .consume_cli_auth_session import ConsumeCliAuthSession
from .create_cli_auth_session import CreateCliAuthSession
from .create_ledger import CreateLedger
from .delete_ledger import DeleteLedger
from .get_cli_auth_session import GetCliAuthSession
from .get_current_user import GetCurrentUser
from .get_ledger import GetLedger
from .list_ledgers import ListLedgers
from .logout import Logout


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def logout(self, **kwargs: Any) -> Logout:
        query = gql("""
            mutation Logout {
              logout {
                success
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="Logout", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Logout.model_validate(data)

    def get_current_user(self, **kwargs: Any) -> GetCurrentUser:
        query = gql("""
            query GetCurrentUser {
              userProfile {
                id
                email
                username
                tier
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="GetCurrentUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetCurrentUser.model_validate(data)

    def create_cli_auth_session(self, **kwargs: Any) -> CreateCliAuthSession:
        query = gql("""
            mutation CreateCliAuthSession {
              createCliAuthSession {
                sessionId
                expiresAt
              }
            }
            """)
        variables: dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="CreateCliAuthSession",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CreateCliAuthSession.model_validate(data)

    def get_cli_auth_session(self, session_id: str, **kwargs: Any) -> GetCliAuthSession:
        query = gql("""
            query GetCliAuthSession($sessionId: String!) {
              getCliAuthSession(sessionId: $sessionId) {
                status
              }
            }
            """)
        variables: dict[str, object] = {"sessionId": session_id}
        response = self.execute(
            query=query,
            operation_name="GetCliAuthSession",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetCliAuthSession.model_validate(data)

    def consume_cli_auth_session(
        self, session_id: str, **kwargs: Any
    ) -> ConsumeCliAuthSession:
        query = gql("""
            mutation ConsumeCliAuthSession($sessionId: String!) {
              consumeCliAuthSession(sessionId: $sessionId) {
                token
                expireAt
              }
            }
            """)
        variables: dict[str, object] = {"sessionId": session_id}
        response = self.execute(
            query=query,
            operation_name="ConsumeCliAuthSession",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return ConsumeCliAuthSession.model_validate(data)

    def create_ledger(
        self,
        name: str,
        private: Union[Optional[bool], UnsetType] = UNSET,
        description: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> CreateLedger:
        query = gql("""
            mutation CreateLedger($name: String!, $private: Boolean, $description: String) {
              createLedger(name: $name, private: $private, description: $description) {
                id
                name
                fullName
                sshUrl
                httpUrl
                private
                empty
                createdAt
                updatedAt
              }
            }
            """)
        variables: dict[str, object] = {
            "name": name,
            "private": private,
            "description": description,
        }
        response = self.execute(
            query=query, operation_name="CreateLedger", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateLedger.model_validate(data)

    def list_ledgers(
        self,
        limit: Union[Optional[float], UnsetType] = UNSET,
        page: Union[Optional[float], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> ListLedgers:
        query = gql("""
            query ListLedgers($limit: Float, $page: Float) {
              listLedgers(limit: $limit, page: $page) {
                id
                name
                fullName
                httpUrl
                sshUrl
                private
                empty
                createdAt
                updatedAt
              }
            }
            """)
        variables: dict[str, object] = {"limit": limit, "page": page}
        response = self.execute(
            query=query, operation_name="ListLedgers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListLedgers.model_validate(data)

    def delete_ledger(self, ledger_id: str, **kwargs: Any) -> DeleteLedger:
        query = gql("""
            mutation DeleteLedger($ledgerId: String!) {
              deleteLedger(ledgerId: $ledgerId) {
                ledgerId
              }
            }
            """)
        variables: dict[str, object] = {"ledgerId": ledger_id}
        response = self.execute(
            query=query, operation_name="DeleteLedger", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteLedger.model_validate(data)

    def get_ledger(self, ledger_id: str, **kwargs: Any) -> GetLedger:
        query = gql("""
            query GetLedger($ledgerId: String!) {
              getLedger(ledgerId: $ledgerId) {
                id
                name
                fullName
                sshUrl
                httpUrl
                private
                empty
                createdAt
                updatedAt
              }
            }
            """)
        variables: dict[str, object] = {"ledgerId": ledger_id}
        response = self.execute(
            query=query, operation_name="GetLedger", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetLedger.model_validate(data)
