# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class ConsumeCliAuthSession(BaseModel):
    consume_cli_auth_session: "ConsumeCliAuthSessionConsumeCliAuthSession" = Field(
        alias="consumeCliAuthSession"
    )


class ConsumeCliAuthSessionConsumeCliAuthSession(BaseModel):
    token: str
    expire_at: str = Field(alias="expireAt")


ConsumeCliAuthSession.model_rebuild()
