# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class CreateCliAuthSession(BaseModel):
    create_cli_auth_session: "CreateCliAuthSessionCreateCliAuthSession" = Field(
        alias="createCliAuthSession"
    )


class CreateCliAuthSessionCreateCliAuthSession(BaseModel):
    device_code: str = Field(alias="deviceCode")
    user_code: str = Field(alias="userCode")
    expires_at: str = Field(alias="expiresAt")
    poll_interval_seconds: int = Field(alias="pollIntervalSeconds")


CreateCliAuthSession.model_rebuild()
