# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class CreateCliAuthSession(BaseModel):
    create_cli_auth_session: "CreateCliAuthSessionCreateCliAuthSession" = Field(
        alias="createCliAuthSession"
    )


class CreateCliAuthSessionCreateCliAuthSession(BaseModel):
    session_id: str = Field(alias="sessionId")
    expires_at: str = Field(alias="expiresAt")


CreateCliAuthSession.model_rebuild()
