# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class DeleteLedger(BaseModel):
    delete_ledger: "DeleteLedgerDeleteLedger" = Field(alias="deleteLedger")


class DeleteLedgerDeleteLedger(BaseModel):
    ledger_id: str = Field(alias="ledgerId")


DeleteLedger.model_rebuild()
