# Generated by ariadne-codegen
# Source: graphql/schema.graphql

from enum import Enum


class ReportStatus(str, Enum):
    OFF = "OFF"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class CliAuthStatus(str, Enum):
    PENDING = "PENDING"
    AUTHORIZED = "AUTHORIZED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"
    CONSUMED = "CONSUMED"


class FeedSource(str, Enum):
    BLOG = "BLOG"
    LEDGER_RSS = "LEDGER_RSS"


class LedgerEntryType(str, Enum):
    TRANSACTION = "TRANSACTION"
    COMMODITY = "COMMODITY"
    PRICE = "PRICE"
    NOTE = "NOTE"
    BALANCE = "BALANCE"
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    BUDGET = "BUDGET"
    DOCUMENT = "DOCUMENT"
    EVENT = "EVENT"


class BudgetInterval(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    YEARLY = "YEARLY"
