# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class GetLedger(BaseModel):
    get_ledger: "GetLedgerGetLedger" = Field(alias="getLedger")


class GetLedgerGetLedger(BaseModel):
    id: str
    name: str
    full_name: str = Field(alias="fullName")
    ssh_url: str = Field(alias="sshUrl")
    http_url: str = Field(alias="httpUrl")
    private: bool
    empty: bool
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")


GetLedger.model_rebuild()
