# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel
from .enums import CliAuthStatus


class GetCliAuthSession(BaseModel):
    get_cli_auth_session: "GetCliAuthSessionGetCliAuthSession" = Field(
        alias="getCliAuthSession"
    )


class GetCliAuthSessionGetCliAuthSession(BaseModel):
    status: CliAuthStatus


GetCliAuthSession.model_rebuild()
