# Generated by ariadne-codegen
# Source: graphql/operations/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetCurrentUser(BaseModel):
    user_profile: Optional["GetCurrentUserUserProfile"] = Field(alias="userProfile")


class GetCurrentUserUserProfile(BaseModel):
    id: str
    email: str
    username: Optional[str]
    tier: str


GetCurrentUser.model_rebuild()
