# Generated by ariadne-codegen
# Source: graphql/schema.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BudgetInterval, LedgerEntryType


class JournalQueryInput(BaseModel):
    account: Optional[str] = None
    filter_: Optional[str] = Field(alias="filter", default=None)
    time: Optional[str] = None
    limit: Optional[float] = 20
    offset: Optional[float] = 0
    directive_types: Optional[list[str]] = Field(alias="directiveTypes", default=None)
    transaction_subtypes: Optional[list[str]] = Field(
        alias="transactionSubtypes", default=None
    )
    document_subtypes: Optional[list[str]] = Field(
        alias="documentSubtypes", default=None
    )
    custom_subtypes: Optional[list[str]] = Field(alias="customSubtypes", default=None)


class PlaintextJournalQueryInput(BaseModel):
    account: Optional[str] = None
    filter_: Optional[str] = Field(alias="filter", default=None)
    time: Optional[str] = None


class AccountJournalQueryInput(BaseModel):
    account: str
    filter_: Optional[str] = Field(alias="filter", default=None)
    time: Optional[str] = None
    limit: Optional[float] = 20
    offset: Optional[float] = 0
    with_children: Optional[bool] = True
    conversion: Optional[str] = "at_cost"


class TransactionToCategorizeInput(BaseModel):
    row_index: int = Field(alias="rowIndex")
    date: str
    payee: str
    description: str
    amount: float


class AddEntryInput(BaseModel):
    type_: LedgerEntryType = Field(alias="type")
    transaction: Optional["LedgerTransactionInput"] = None
    commodity: Optional["LedgerCommodityInput"] = None
    price: Optional["LedgerPriceInput"] = None
    note: Optional["LedgerNoteInput"] = None
    balance: Optional["LedgerBalanceInput"] = None
    open: Optional["LedgerOpenInput"] = None
    close: Optional["LedgerCloseInput"] = None
    budget: Optional["LedgerBudgetInput"] = None
    document: Optional["LedgerDocumentInput"] = None
    event: Optional["LedgerEventInput"] = None


class LedgerTransactionInput(BaseModel):
    date: str
    flag: str
    payee: Optional[str] = None
    narration: Optional[str] = None
    postings: list["LedgerPostingInput"]
    tags: Optional[list[str]] = None
    links: Optional[list[str]] = None


class LedgerPostingInput(BaseModel):
    units: "LedgerAmountInput"
    account: str
    price: Optional["LedgerAmountInput"] = None
    flag: Optional[str] = None


class LedgerAmountInput(BaseModel):
    number: str
    currency: str


class LedgerCommodityInput(BaseModel):
    date: str
    currency: str


class LedgerPriceInput(BaseModel):
    date: str
    currency: str
    amount: "LedgerAmountInput"


class LedgerNoteInput(BaseModel):
    date: str
    content: str
    account: str


class LedgerBalanceInput(BaseModel):
    date: str
    account: str
    amount: "LedgerAmountInput"


class LedgerOpenInput(BaseModel):
    date: str
    account: str
    currencies: list[str]


class LedgerCloseInput(BaseModel):
    date: str
    account: str


class LedgerBudgetInput(BaseModel):
    date: str
    account: str
    interval: BudgetInterval
    amount: "LedgerAmountInput"


class LedgerDocumentInput(BaseModel):
    date: str
    account: str
    filename: str
    tags: Optional[list[str]] = None
    links: Optional[list[str]] = None


class LedgerEventInput(BaseModel):
    date: str
    type_: str = Field(alias="type")
    description: str


class InsertReceiptTransactionInput(BaseModel):
    date: str
    payee: str
    description: str
    postings: list["ReceiptPostingInput"]
    document_account: str = Field(alias="documentAccount")


class ReceiptPostingInput(BaseModel):
    account: str
    amount_number: str = Field(alias="amountNumber")
    amount_currency: str = Field(alias="amountCurrency")


class DeleteSourceSliceInput(BaseModel):
    entry_hash: str = Field(alias="entryHash")
    sha_256_sum: str = Field(alias="sha256sum")


class DeleteMultiSourceSlicesInput(BaseModel):
    entries: list["DeleteMultiSourceSliceItemInput"]


class DeleteMultiSourceSliceItemInput(BaseModel):
    entry_hash: str = Field(alias="entryHash")
    sha_256_sum: str = Field(alias="sha256sum")


class UpdateSourceSliceInput(BaseModel):
    entry_hash: str = Field(alias="entryHash")
    sha_256_sum: str = Field(alias="sha256sum")
    new_content: str = Field(alias="newContent")


class EntryInput(BaseModel):
    date: str
    flag: str
    meta: Any
    narration: str
    payee: str
    postings: list["PostingInput"]
    type_: str = Field(alias="type")


class PostingInput(BaseModel):
    account: str
    amount: str


class CreatePRFromPatchInput(BaseModel):
    ledger_owner: str = Field(alias="ledgerOwner")
    ledger_name: str = Field(alias="ledgerName")
    title: str
    description: Optional[str] = None
    base_branch: str = Field(alias="baseBranch", default="main")
    changes: list["FileChangeInput"]


class FileChangeInput(BaseModel):
    path: str
    content: str


class PlaidTransactionSubmitInput(BaseModel):
    transaction_id: str = Field(alias="transactionId")
    target_account: str = Field(alias="targetAccount")


AddEntryInput.model_rebuild()
LedgerTransactionInput.model_rebuild()
LedgerPostingInput.model_rebuild()
LedgerPriceInput.model_rebuild()
LedgerBalanceInput.model_rebuild()
LedgerBudgetInput.model_rebuild()
InsertReceiptTransactionInput.model_rebuild()
DeleteMultiSourceSlicesInput.model_rebuild()
EntryInput.model_rebuild()
CreatePRFromPatchInput.model_rebuild()
