# Generated by ariadne-codegen
# Source: graphql/operations/

from pydantic import Field

from .base_model import BaseModel


class ListLedgers(BaseModel):
    list_ledgers: list["ListLedgersListLedgers"] = Field(alias="listLedgers")


class ListLedgersListLedgers(BaseModel):
    id: str
    name: str
    full_name: str = Field(alias="fullName")
    http_url: str = Field(alias="httpUrl")
    ssh_url: str = Field(alias="sshUrl")
    private: bool
    empty: bool
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")


ListLedgers.model_rebuild()
