/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/*
 * ---------------------------------------------------------------
 * ## LEDGER API DTO TYPES                                       ##
 * ##                                                            ##
 * ## The accounting-compute engine's output contract / the     ##
 * ## GraphQL DTO shapes. These interfaces/enums were originally ##
 * ## generated by swagger-typescript-api (acacode) from the    ##
 * ## Python ledger service's OpenAPI spec; the generated HTTP   ##
 * ## client (Api/HttpClient classes) has been removed — only   ##
 * ## the type definitions remain. Nothing here performs I/O.    ##
 * ---------------------------------------------------------------
 */

/**
 * WebhookType
 * Supported webhook types
 */
export enum WebhookType {
  Dingtalk = "dingtalk",
  Discord = "discord",
  Gitea = "gitea",
  Gogs = "gogs",
  Msteams = "msteams",
  Slack = "slack",
  Telegram = "telegram",
  Feishu = "feishu",
  Wechatwork = "wechatwork",
  Packagist = "packagist",
}

/**
 * WebhookEvent
 * Supported webhook events
 */
export enum WebhookEvent {
  Create = "create",
  Delete = "delete",
  Fork = "fork",
  Push = "push",
  Issues = "issues",
  IssueAssign = "issue_assign",
  IssueLabel = "issue_label",
  IssueMilestone = "issue_milestone",
  IssueComment = "issue_comment",
  PullRequest = "pull_request",
  PullRequestAssign = "pull_request_assign",
  PullRequestLabel = "pull_request_label",
  PullRequestMilestone = "pull_request_milestone",
  PullRequestComment = "pull_request_comment",
  PullRequestReviewApproved = "pull_request_review_approved",
  PullRequestReviewRejected = "pull_request_review_rejected",
  PullRequestReviewComment = "pull_request_review_comment",
  PullRequestSync = "pull_request_sync",
  PullRequestReviewRequest = "pull_request_review_request",
  Wiki = "wiki",
  Repository = "repository",
  Release = "release",
  Package = "package",
  Status = "status",
  WorkflowJob = "workflow_job",
}

/**
 * TransactionSubtype
 * Enum for transaction subtypes.
 */
export enum TransactionSubtype {
  Cleared = "cleared",
  Pending = "pending",
  Other = "other",
}

/**
 * DocumentSubtype
 * Enum for document subtypes.
 */
export enum DocumentSubtype {
  Discovered = "discovered",
  Linked = "linked",
}

/**
 * DirectiveType
 * Enum for Beancount directive types.
 */
export enum DirectiveType {
  Transaction = "Transaction",
  Balance = "Balance",
  Commodity = "Commodity",
  Close = "Close",
  Custom = "Custom",
  Document = "Document",
  Event = "Event",
  Note = "Note",
  Open = "Open",
  Pad = "Pad",
  Price = "Price",
}

/**
 * CustomSubtype
 * Enum for custom subtypes.
 */
export enum CustomSubtype {
  Budget = "budget",
}

/**
 * AccountDataPublic
 * Public schema for detailed account data.
 */
export interface AccountDataPublic {
  /** Close Date */
  close_date?: string | null;
  /** Meta */
  meta?: Record<string, string | number | boolean | null> | null;
  /** Uptodate Status */
  uptodate_status?: string | null;
  /** Balance String */
  balance_string?: string | null;
  last_entry?: LastEntryPublic | null;
}

/**
 * AccountJournalEntryPublic
 * Account journal entry with change and balance information.
 */
export interface AccountJournalEntryPublic {
  /**
   * Entry
   * The journal entry
   */
  entry:
    | JournalTransactionPublic
    | JournalBalancePublic
    | JournalCommodityPublic
    | JournalClosePublic
    | JournalCustomPublic
    | JournalDocumentPublic
    | JournalEventPublic
    | JournalNotePublic
    | JournalOpenPublic
    | JournalPadPublic
    | JournalPricePublic;
  /**
   * Change
   * Change amounts for this entry
   */
  change: Record<string, string>;
  /**
   * Balance
   * Running balance after this entry
   */
  balance: Record<string, string>;
}

/**
 * AccountJournalResponsePublic
 * Response schema for account journal entries.
 */
export interface AccountJournalResponsePublic {
  /**
   * Items
   * Account journal entries
   */
  items: AccountJournalEntryPublic[];
  /**
   * Total
   * Total number of account journal entries
   */
  total: number;
  /**
   * Account
   * Account name
   */
  account: string;
  /**
   * With Children
   * Whether subaccounts were included
   */
  with_children: boolean;
}

/**
 * AccountLastEntryPublic
 * Public schema for account last entry information.
 */
export interface AccountLastEntryPublic {
  /** Account */
  account: string;
  /** Date */
  date: string | null;
  /** Balance */
  balance: Record<string, string>;
}

/**
 * AccountReportPublic
 * Public schema for account report.
 */
export interface AccountReportPublic {
  /** Linechart Data */
  linechart_data: DateAndBalancePublic[];
  /** Interval Totals Data */
  interval_totals_data: DateAndBalancePublic[];
  /** Account Balance Data */
  account_balance_data: DateAndBalancePublic[];
}

/**
 * Amount
 * An amount in some currency.
 */
export interface Amount {
  /**
   * Number
   * Number of units in the amount
   */
  number: number | string;
  /**
   * Currency
   * Currency of the amount
   */
  currency: string;
}

/**
 * AttributesPublic
 * Public schema for attributes.
 */
export interface AttributesPublic {
  /** Accounts */
  accounts: string[];
  /** Tags */
  tags: string[];
  /** Links */
  links: string[];
  /** Years */
  years: string[];
  /** Currencies */
  currencies: string[];
  /** Payees */
  payees: string[];
}

/**
 * Balance
 * A Beancount Balance directive.
 */
export interface Balance {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Account
   * Account to assert the balance for
   */
  account: string;
  /** Expected balance amount for the account */
  amount: Amount;
  /** Difference between expected and actual balance amounts */
  diff_amount?: Amount | null;
}

/**
 * BalanceSheetDataPublic
 * Public schema for balance sheet data for visualization.
 */
export interface BalanceSheetDataPublic {
  /** Net Worth Data */
  net_worth_data: DateAndBalancePublic[];
  /** Assets Data */
  assets_data: DateAndBalancePublic[];
  /** Liabilities Data */
  liabilities_data: DateAndBalancePublic[];
  /** Equity Data */
  equity_data: DateAndBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  assets_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  liabilities_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  equity_hierarchy_data: SerializableTreeNodePublic;
}

/**
 * BcioOptionsPublic
 * Public schema for BcioOptions (beancount.io-specific options).
 */
export interface BcioOptionsPublic {
  /** Default File */
  default_file: string;
  /** Transaction File */
  transaction_file: string | null;
  /** Account File */
  account_file: string | null;
  /** Price File */
  price_file: string | null;
  /** Balance File */
  balance_file: string | null;
  /** Note File */
  note_file: string | null;
  /** Pad File */
  pad_file: string | null;
  /** Budget File */
  budget_file: string | null;
  /** Receipt Base Folder */
  receipt_base_folder: string | null;
  /** Receipt Storage */
  receipt_storage: string | null;
  /** Document File */
  document_file: string | null;
}

/**
 * BeancountErrorPublic
 * Public schema for BeancountError.
 */
export interface BeancountErrorPublic {
  source?: BeancountErrorSourcePublic | null;
  /** Message */
  message: string;
}

/**
 * BeancountErrorSourcePublic
 * Public schema for BeancountErrorSource.
 */
export interface BeancountErrorSourcePublic {
  /** Filename */
  filename: string;
  /** Lineno */
  lineno: number;
}

/**
 * BeancountOptionsPublic
 * Public schema for BeancountOptions.
 */
export interface BeancountOptionsPublic {
  /** Title */
  title: string;
  /** Name Assets */
  name_assets: string;
  /** Name Liabilities */
  name_liabilities: string;
  /** Name Equity */
  name_equity: string;
  /** Name Income */
  name_income: string;
  /** Name Expenses */
  name_expenses: string;
  /** Account Current Conversions */
  account_current_conversions: string;
  /** Account Current Earnings */
  account_current_earnings: string;
  /** Render Commas */
  render_commas: boolean;
  /** Operating Currency */
  operating_currency: string[];
}

/** Body_webhookGiteaPreReceiveCheck */
export interface BodyWebhookGiteaPreReceiveCheck {
  /** Owner */
  owner: string;
  /** Repo */
  repo: string;
  /**
   * Archive
   * @format binary
   */
  archive: File;
  /** Old Archive */
  old_archive?: File | null;
}

/**
 * BulkBalanceEntry
 * A balance entry in a bulk request.
 */
export interface BulkBalanceEntry {
  /** Type */
  type: "balance";
  /** Balance to add */
  item: Balance;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkCloseEntry
 * A close account entry in a bulk request.
 */
export interface BulkCloseEntry {
  /** Type */
  type: "close";
  /** Close directive to add */
  item: Close;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkCommodityEntry
 * A commodity entry in a bulk request.
 */
export interface BulkCommodityEntry {
  /** Type */
  type: "commodity";
  /** Commodity to add */
  item: Commodity;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkCustomEntry
 * A custom directive entry in a bulk request.
 */
export interface BulkCustomEntry {
  /** Type */
  type: "custom";
  /** Custom directive to add */
  item: CustomDirectiveCreate;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkDocumentEntry
 * A document directive entry in a bulk request.
 */
export interface BulkDocumentEntry {
  /** Type */
  type: "document";
  /** Document directive to add */
  item: DocumentCreate;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkEventEntry
 * An event entry in a bulk request.
 */
export interface BulkEventEntry {
  /** Type */
  type: "event";
  /** Event directive to add */
  item: Event;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkNoteEntry
 * A note entry in a bulk request.
 */
export interface BulkNoteEntry {
  /** Type */
  type: "note";
  /** Note to add */
  item: Note;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkOpenEntry
 * An open account entry in a bulk request.
 */
export interface BulkOpenEntry {
  /** Type */
  type: "open";
  /** Open directive to add */
  item: Open;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkPriceEntry
 * A price entry in a bulk request.
 */
export interface BulkPriceEntry {
  /** Type */
  type: "price";
  /** Price to add */
  item: Price;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * BulkTransactionEntry
 * A transaction entry in a bulk request.
 */
export interface BulkTransactionEntry {
  /** Type */
  type: "transaction";
  /** Transaction to add */
  item: Transaction;
  /**
   * Filename
   * Target file path (defaults to the request filename or main.bean)
   */
  filename?: string | null;
}

/**
 * Close
 * A Beancount Close directive.
 */
export interface Close {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Account
   * Account of the directive
   */
  account: string;
}

/** CommitPublic */
export interface CommitPublic {
  /** Sha */
  sha: string;
  author?: UserPublic | null;
  committer?: UserPublic | null;
  commit?: RepoCommitPublic | null;
  /** Created */
  created?: string | null;
}

/**
 * Commodity
 * A Beancount Commodity directive.
 */
export interface Commodity {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Currency
   * Currency
   */
  currency: string;
}

/**
 * CommodityPairWithPricesPublic
 * A pair of commodities and prices for them.
 */
export interface CommodityPairWithPricesPublic {
  /** Base */
  base: string;
  /** Quote */
  quote: string;
  /** Prices */
  prices: PricePointPublic[];
}

/**
 * ContextPublic
 * Context for an entry.
 */
export interface ContextPublic {
  /**
   * Entry
   * Serialized entry
   */
  entry:
    | JournalTransactionPublic
    | JournalBalancePublic
    | JournalCommodityPublic
    | JournalClosePublic
    | JournalCustomPublic
    | JournalDocumentPublic
    | JournalEventPublic
    | JournalNotePublic
    | JournalOpenPublic
    | JournalPadPublic
    | JournalPricePublic;
  /**
   * Balances Before
   * Account balances before the entry
   */
  balances_before?: Record<string, string[]> | null;
  /**
   * Balances After
   * Account balances after the entry
   */
  balances_after?: Record<string, string[]> | null;
  /**
   * Sha256Sum
   * SHA256 hash of the entry source
   */
  sha256sum: string;
  /**
   * Slice
   * Source code slice of the entry
   */
  slice: string;
}

/**
 * Cost
 * A cost (basically an amount with date and label).
 */
export interface Cost {
  /**
   * Number
   * Number of units in the cost
   */
  number: number | string;
  /**
   * Currency
   * Currency of the cost
   */
  currency: string;
  /**
   * Date
   * Date of the cost
   * @format date
   */
  date: string;
  /**
   * Label
   * Label of the cost
   */
  label?: string | null;
}

/** CreateUserRequest */
export interface CreateUserRequest {
  /** Username */
  username: string;
  /** Password */
  password: string;
  /**
   * Email
   * @format email
   */
  email: string;
}

/**
 * CreateWebhookRequest
 * Request model for creating a webhook
 */
export interface CreateWebhookRequest {
  /**
   * Active
   * Whether the webhook is active
   * @default false
   */
  active?: boolean | null;
  /**
   * Authorization Header
   * Authorization header value
   */
  authorization_header?: string | null;
  /**
   * Branch Filter
   * Branch filter pattern
   */
  branch_filter?: string | null;
  /**
   * Config
   * Webhook configuration (must include 'content_type' and 'url')
   */
  config: Record<string, string>;
  /**
   * Events
   * List of events to trigger webhook
   */
  events?: WebhookEvent[] | null;
  /** Webhook type (dingtalk, discord, gitea, gogs, msteams, slack, telegram, feishu, wechatwork, packagist) */
  type: WebhookType;
}

/**
 * CustomDirectiveCreate
 * Input model for creating a Custom directive.
 */
export interface CustomDirectiveCreate {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Type
   * Custom directive type name (e.g. 'budget')
   */
  type: string;
  /**
   * Values
   * Values for the directive
   */
  values?: (
    | ({
        kind: "account";
      } & CustomDirectiveValueAccount)
    | ({
        kind: "amount";
      } & CustomDirectiveValueAmount)
    | ({
        kind: "number";
      } & CustomDirectiveValueNumber)
    | ({
        kind: "text";
      } & CustomDirectiveValueText)
  )[];
}

/**
 * CustomDirectiveValueAccount
 * An account reference in a custom directive (written unquoted in the beancount file).
 */
export interface CustomDirectiveValueAccount {
  /** Kind */
  kind: "account";
  /**
   * Value
   * Account name (will appear unquoted in beancount)
   */
  value: string;
}

/**
 * CustomDirectiveValueAmount
 * An amount value in a custom directive.
 */
export interface CustomDirectiveValueAmount {
  /** Kind */
  kind: "amount";
  /**
   * Number
   * Amount number
   */
  number: number | string;
  /**
   * Currency
   * Amount currency
   */
  currency: string;
}

/**
 * CustomDirectiveValueNumber
 * A numeric value in a custom directive.
 */
export interface CustomDirectiveValueNumber {
  /** Kind */
  kind: "number";
  /**
   * Value
   * Numeric value
   */
  value: number | string;
}

/**
 * CustomDirectiveValueText
 * A string value in a custom directive (will be quoted in the beancount file).
 */
export interface CustomDirectiveValueText {
  /** Kind */
  kind: "text";
  /**
   * Value
   * String value (will appear quoted in beancount)
   */
  value: string;
}

/**
 * DateAndBalancePublic
 * Public schema for balance at a date.
 */
export interface DateAndBalancePublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Balance */
  balance: Record<string, string>;
}

/**
 * DateAndBalanceWithAccountBalancePublic
 * Public schema for balance at a date with per-account breakdown.
 */
export interface DateAndBalanceWithAccountBalancePublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Balance */
  balance: Record<string, string>;
  /** Account Balances */
  account_balances: Record<string, Record<string, string>>;
}

/**
 * DeleteMultiSourceSliceItem
 * A single entry hash and sha256sum pair for bulk deletion.
 */
export interface DeleteMultiSourceSliceItem {
  /**
   * Entry Hash
   * Hash of the entry to delete
   */
  entry_hash: string;
  /**
   * Sha256Sum
   * SHA256 hash of the current entry source for validation
   */
  sha256sum: string;
}

/**
 * DeleteMultiSourceSlicesRequest
 * Request schema for deleting multiple source slices in a single operation.
 */
export interface DeleteMultiSourceSlicesRequest {
  /**
   * Entries
   * List of entries to delete
   */
  entries: DeleteMultiSourceSliceItem[];
}

/**
 * DeleteMultiSourceSlicesResponse
 * Response schema for deleting multiple source slices.
 */
export interface DeleteMultiSourceSlicesResponse {
  /**
   * Message
   * Success message
   */
  message: string;
  /**
   * Deleted Hashes
   * Hashes of the deleted entries
   */
  deleted_hashes: string[];
}

/**
 * DeleteSourceSliceRequest
 * Request schema for deleting a source slice.
 */
export interface DeleteSourceSliceRequest {
  /**
   * Entry Hash
   * Hash of the entry to delete
   */
  entry_hash: string;
  /**
   * Sha256Sum
   * SHA256 hash of the current entry source for validation
   */
  sha256sum: string;
}

/**
 * DeleteSourceSliceResponse
 * Response schema for deleting a source slice.
 */
export interface DeleteSourceSliceResponse {
  /**
   * Message
   * Success message
   */
  message: string;
  /**
   * Entry Hash
   * Hash of the deleted entry
   */
  entry_hash: string;
}

/**
 * DocumentCreate
 * Input model for creating a Document directive.
 */
export interface DocumentCreate {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Account
   * Account the document is attached to
   */
  account: string;
  /**
   * Filename
   * Path to the document file within the repository
   */
  filename: string;
  /**
   * Tags
   * Entry tags
   * @uniqueItems true
   */
  tags?: string[];
  /**
   * Links
   * Entry links
   * @uniqueItems true
   */
  links?: string[];
}

/**
 * DocumentPublic
 * Public schema for beancount documents.
 */
export interface DocumentPublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Account */
  account: string;
  /** Filename */
  filename: string;
  /** Tags */
  tags?: string[] | null;
  /** Links */
  links?: string[] | null;
  /** Meta */
  meta?: Record<string, string | number | boolean | null> | null;
}

/**
 * EditUserRequest
 * Request schema for editing a user
 */
export interface EditUserRequest {
  /** Login Name */
  login_name: string;
  /** Source Id */
  source_id: number;
  /** Active */
  active?: boolean | null;
  /** Admin */
  admin?: boolean | null;
  /** Allow Create Organization */
  allow_create_organization?: boolean | null;
  /** Allow Git Hook */
  allow_git_hook?: boolean | null;
  /** Allow Import Local */
  allow_import_local?: boolean | null;
  /** Description */
  description?: string | null;
  /** Email */
  email?: string | null;
  /** Full Name */
  full_name?: string | null;
  /** Location */
  location?: string | null;
  /** Max Repo Creation */
  max_repo_creation?: number | null;
  /** Must Change Password */
  must_change_password?: boolean | null;
  /** Password */
  password?: string | null;
  /** Prohibit Login */
  prohibit_login?: boolean | null;
  /** Restricted */
  restricted?: boolean | null;
  /** Visibility */
  visibility?: string | null;
  /** Website */
  website?: string | null;
}

/**
 * EntriesCountPerTypePublic
 * Public schema for entries count per type.
 */
export interface EntriesCountPerTypePublic {
  /** Type */
  type: string;
  /** Number */
  number: number;
}

/**
 * EntryAddBulkEntriesRequest
 * Request schema for adding multiple entries of mixed directive types in one commit.
 */
export interface EntryAddBulkEntriesRequest {
  /**
   * Entries
   * Entries to add, in submission order
   */
  entries: (
    | ({
        type: "balance";
      } & BulkBalanceEntry)
    | ({
        type: "close";
      } & BulkCloseEntry)
    | ({
        type: "commodity";
      } & BulkCommodityEntry)
    | ({
        type: "custom";
      } & BulkCustomEntry)
    | ({
        type: "document";
      } & BulkDocumentEntry)
    | ({
        type: "event";
      } & BulkEventEntry)
    | ({
        type: "note";
      } & BulkNoteEntry)
    | ({
        type: "open";
      } & BulkOpenEntry)
    | ({
        type: "price";
      } & BulkPriceEntry)
    | ({
        type: "transaction";
      } & BulkTransactionEntry)
  )[];
  /**
   * Filename
   * Default target file for items that omit their own (defaults to main.bean)
   */
  filename?: string | null;
}

/**
 * ErrorResponse
 * 统一错误响应格式
 */
export interface ErrorResponse {
  /**
   * Success
   * @default false
   */
  success?: boolean;
  /** Error */
  error: string;
  /**
   * Code
   * Machine-readable error code for structured client handling (e.g. 'directive_limit_exceeded')
   */
  code?: string | null;
  /**
   * Details
   * Structured details for `code`, e.g. {'limit': 1000, 'current': 1005}
   */
  details?: Record<string, number | string> | null;
}

/**
 * Event
 * A Beancount Event directive.
 */
export interface Event {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Type
   * Type of the event
   */
  type: string;
  /**
   * Description
   * Description of the event
   */
  description: string;
}

/**
 * EventPublic
 * Public schema for beancount events.
 */
export interface EventPublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Type */
  type: string;
  /** Description */
  description: string;
}

/**
 * FavaOptionsPublic
 * Public schema for FavaOptions.
 */
export interface FavaOptionsPublic {
  /** Account Journal Include Children */
  account_journal_include_children: boolean;
  /** Auto Reload */
  auto_reload: boolean;
  /** Collapse Pattern */
  collapse_pattern: string[];
  /** Conversion Currencies */
  conversion_currencies: string[];
  /** Currency Column */
  currency_column: number;
  /** Default Page */
  default_page: string;
  /** Public schema for FiscalYearEnd. */
  fiscal_year_end: FiscalYearEndPublic;
  /** Indent */
  indent: number;
  /** Invert Income Liabilities Equity */
  invert_income_liabilities_equity: boolean;
  /** Language */
  language: string | null;
  /** Locale */
  locale: string | null;
  /** Show Accounts With Zero Balance */
  show_accounts_with_zero_balance: boolean;
  /** Show Accounts With Zero Transactions */
  show_accounts_with_zero_transactions: boolean;
  /** Show Closed Accounts */
  show_closed_accounts: boolean;
  /** Sidebar Show Queries */
  sidebar_show_queries: number;
  /** Unrealized */
  unrealized: string;
  /** Upcoming Events */
  upcoming_events: number;
  /** Uptodate Indicator Grey Lookback Days */
  uptodate_indicator_grey_lookback_days: number;
  /** Use External Editor */
  use_external_editor: boolean;
}

/**
 * FiscalYearEndPublic
 * Public schema for FiscalYearEnd.
 */
export interface FiscalYearEndPublic {
  /** Month */
  month: number;
  /** Day */
  day: number;
}

/** GitObjectPublic */
export interface GitObjectPublic {
  /** Sha */
  sha: string;
  /** Type */
  type: string;
}

/** HealthCheck */
export interface HealthCheck {
  /** Status */
  status: string;
  /** Timestamp */
  timestamp: string;
}

/**
 * IncomeStatementDataPublic
 * Public schema for income statement data for visualization.
 */
export interface IncomeStatementDataPublic {
  /** Net Profit Data */
  net_profit_data: DateAndBalancePublic[];
  /** Income Data */
  income_data: DateAndBalanceWithAccountBalancePublic[];
  /** Expenses Data */
  expenses_data: DateAndBalanceWithAccountBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  income_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  expenses_hierarchy_data: SerializableTreeNodePublic;
}

/**
 * JournalAmountPublic
 * An amount in some currency.
 */
export interface JournalAmountPublic {
  /**
   * Number
   * Number of units in the amount
   */
  number: string;
  /**
   * Currency
   * Currency of the amount
   */
  currency: string;
}

/**
 * JournalBalancePublic
 * A Beancount Balance directive.
 */
export interface JournalBalancePublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /** Difference amount */
  diff_amount?: JournalAmountPublic | null;
}

/**
 * JournalClosePublic
 * A Beancount Close directive.
 */
export interface JournalClosePublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Account
   * Account of the directive
   */
  account: string;
}

/**
 * JournalCommodityPublic
 * A Beancount Commodity directive.
 */
export interface JournalCommodityPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Currency
   * Currency
   */
  currency: string;
}

/**
 * JournalCostPublic
 * A cost (basically an amount with date and label).
 */
export interface JournalCostPublic {
  /**
   * Number
   * Number of units in the cost
   */
  number: string;
  /**
   * Currency
   * Currency of the cost
   */
  currency: string;
  /**
   * Date
   * Date of the cost
   * @format date
   */
  date: string;
  /**
   * Label
   * Label of the cost
   */
  label?: string | null;
}

/**
 * JournalCustomPublic
 * A Beancount Custom directive.
 */
export interface JournalCustomPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Type
   * Directive type
   */
  type: string;
  /**
   * Values
   * Custom values
   */
  values: (string | number | boolean | null)[];
}

/**
 * JournalDocumentPublic
 * A Beancount Document directive.
 */
export interface JournalDocumentPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Filename
   * Filename of the document
   */
  filename: string;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Tags
   * Entry tags
   * @uniqueItems true
   */
  tags?: string[];
  /**
   * Links
   * Entry links
   * @uniqueItems true
   */
  links?: string[];
}

/**
 * JournalEventPublic
 * A Beancount Event directive.
 */
export interface JournalEventPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Type
   * Type of the event
   */
  type: string;
  /**
   * Description
   * Description of the event
   */
  description: string;
}

/**
 * JournalNotePublic
 * A Beancount Note directive.
 */
export interface JournalNotePublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Comment
   * Note comment
   */
  comment: string;
}

/**
 * JournalOpenPublic
 * A Beancount Open directive.
 */
export interface JournalOpenPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Currencies
   * Valid currencies for the account
   */
  currencies?: string[] | null;
  /**
   * Booking
   * Booking method for the account
   */
  booking?: string | null;
}

/**
 * JournalPadPublic
 * A Beancount Pad directive.
 */
export interface JournalPadPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Source Account
   * Source account of the pad
   */
  source_account: string;
}

/**
 * JournalPostingPublic
 * A Beancount posting.
 */
export interface JournalPostingPublic {
  /** Units of the posting */
  units: JournalAmountPublic;
  /** Cost of the posting */
  cost?: JournalCostPublic | null;
  /**
   * Account
   * Account of the posting
   */
  account: string;
  /** Price of the posting */
  price?: JournalAmountPublic | null;
  /**
   * Meta
   * Metadata of the posting
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Flag
   * Flag of the posting
   */
  flag?: string | null;
}

/**
 * JournalPricePublic
 * A Beancount Price directive.
 */
export interface JournalPricePublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Currency
   * Currency for which this is a price
   */
  currency: string;
  /** Price amount */
  amount: JournalAmountPublic;
}

/**
 * JournalQueryResponsePublic
 * Response schema for exporting journal entries.
 */
export interface JournalQueryResponsePublic {
  /**
   * Items
   * Journal entries
   */
  items: (
    | JournalTransactionPublic
    | JournalBalancePublic
    | JournalCommodityPublic
    | JournalClosePublic
    | JournalCustomPublic
    | JournalDocumentPublic
    | JournalEventPublic
    | JournalNotePublic
    | JournalOpenPublic
    | JournalPadPublic
    | JournalPricePublic
  )[];
  /**
   * Total
   * Total number of journal entries
   */
  total: number;
  /**
   * Is Empty
   * Whether the journal is empty
   */
  is_empty: boolean;
}

/**
 * JournalTransactionPublic
 * A Beancount Transaction directive.
 */
export interface JournalTransactionPublic {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Entry Hash
   * Hash of the entry
   */
  entry_hash: string;
  /** Type of the directive */
  directive_type: DirectiveType;
  /**
   * Flag
   * Flag of the transaction
   */
  flag: string;
  /**
   * Payee
   * Payee of the transaction
   */
  payee?: string | null;
  /**
   * Narration
   * Narration of the transaction
   */
  narration?: string | null;
  /**
   * Postings
   * Postings of the transaction
   */
  postings: JournalPostingPublic[];
  /**
   * Tags
   * Entry tags
   * @uniqueItems true
   */
  tags?: string[];
  /**
   * Links
   * Entry links
   * @uniqueItems true
   */
  links?: string[];
}

/**
 * KeyCreate
 * Schema for creating a new public key
 */
export interface KeyCreate {
  /**
   * Key
   * The public key content
   */
  key: string;
  /**
   * Title
   * Title for the public key
   */
  title: string;
  /**
   * Read Only
   * Whether the key is read-only
   * @default false
   */
  read_only?: boolean;
}

/**
 * KeyPublic
 * Public schema for key information (safe for API responses)
 */
export interface KeyPublic {
  /** Id */
  id: number;
  /** Fingerprint */
  fingerprint: string;
  /** Key */
  key: string;
  /** Last Used At */
  last_used_at?: string | null;
  /** Title */
  title: string;
  /**
   * Created At
   * @format date-time
   */
  created_at: string;
}

/**
 * LastEntryPublic
 * Public schema for the last entry of an account.
 */
export interface LastEntryPublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Entry Hash */
  entry_hash: string;
}

/** LedgerAddCollaboratorOptions */
export interface LedgerAddCollaboratorOptions {
  /** Permission */
  permission?: "read" | "write" | "admin" | null;
}

/** LedgerChangeFileOperation */
export interface LedgerChangeFileOperation {
  /** Operation */
  operation: "create" | "update" | "delete";
  /** Path */
  path: string;
  /** Content */
  content?: string | null;
  /** From Path */
  from_path?: string | null;
  /** Sha */
  sha?: string | null;
}

/** LedgerChangeFilesOptions */
export interface LedgerChangeFilesOptions {
  /** Files */
  files: LedgerChangeFileOperation[];
  /** Message */
  message?: string | null;
  /** Branch */
  branch?: string | null;
  /** New Branch */
  new_branch?: string | null;
}

/** LedgerCollaboratorPermission */
export interface LedgerCollaboratorPermission {
  /** Permission */
  permission?: string | null;
  /** Role Name */
  role_name?: string | null;
  user?: UserPublic | null;
}

/** LedgerCreate */
export interface LedgerCreate {
  /** Name */
  name: string;
  /** Description */
  description?: string | null;
  /** Private */
  private?: boolean | null;
  /** Files */
  files: Record<string, string>;
}

/** LedgerCreateFileOptions */
export interface LedgerCreateFileOptions {
  /** Path */
  path: string;
  /** Content */
  content: string;
  /** Message */
  message?: string | null;
}

/** LedgerDeleteFileOptions */
export interface LedgerDeleteFileOptions {
  /** Path */
  path: string;
  /** Sha */
  sha: string;
  /** Message */
  message?: string | null;
}

/** LedgerFileContentPublic */
export interface LedgerFileContentPublic {
  /** Name */
  name: string;
  /** Path */
  path: string;
  /** Type */
  type: "file" | "dir";
  /** Sha */
  sha: string;
  /** Size */
  size: number;
  /** Content */
  content?: string | null;
  /** Encoding */
  encoding?: string | null;
  /** Last Commit Sha */
  last_commit_sha?: string | null;
  /** Last Committer Date */
  last_committer_date?: string | null;
  /** Last Author Date */
  last_author_date?: string | null;
}

/** LedgerGetFilesContentOptions */
export interface LedgerGetFilesContentOptions {
  /** Files */
  files: string[];
}

/** LedgerPublic */
export interface LedgerPublic {
  /** Id */
  id: number;
  /** Name */
  name: string;
  /** Description */
  description?: string | null;
  /** Full Name */
  full_name: string;
  /** Empty */
  empty: boolean;
  /** Private */
  private: boolean;
  /** Size */
  size: number;
  /**
   * Created At
   * @format date-time
   */
  created_at: string;
  /**
   * Updated At
   * @format date-time
   */
  updated_at: string;
  permissions?: PermissionPublic | null;
}

/**
 * LedgerSearchResults
 * Search results for ledgers
 */
export interface LedgerSearchResults {
  /** Data */
  data: LedgerPublic[];
  /** Ok */
  ok?: boolean | null;
}

/** LedgerUpdate */
export interface LedgerUpdate {
  /** Name */
  name?: string | null;
  /** Description */
  description?: string | null;
  /** Private */
  private?: boolean | null;
}

/** LedgerUpdateFileOptions */
export interface LedgerUpdateFileOptions {
  /** Path */
  path: string;
  /** Content */
  content: string;
  /** Sha */
  sha: string;
  /** Message */
  message?: string | null;
}

/**
 * Note
 * A Beancount Note directive.
 */
export interface Note {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Comment
   * Note comment
   */
  comment: string;
}

/**
 * Open
 * A Beancount Open directive.
 */
export interface Open {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Account
   * Account of the directive
   */
  account: string;
  /**
   * Currencies
   * Valid currencies for the account
   */
  currencies: string[];
}

/**
 * OverviewPublic
 * Public schema for overview endpoint.
 */
export interface OverviewPublic {
  /** Net Worth Data */
  net_worth_data: DateAndBalancePublic[];
  /** Assets Data */
  assets_data: DateAndBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  assets_hierarchy_data: SerializableTreeNodePublic;
  /** Liabilities Data */
  liabilities_data: DateAndBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  liabilities_hierarchy_data: SerializableTreeNodePublic;
  /** Expenses Interval Data */
  expenses_interval_data: DateAndBalanceWithAccountBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  expenses_hierarchy_data: SerializableTreeNodePublic;
  /** Expenses Data */
  expenses_data: DateAndBalancePublic[];
  /** Income Interval Data */
  income_interval_data: DateAndBalanceWithAccountBalancePublic[];
  /** A serializable tree node for account hierarchy. */
  income_hierarchy_data: SerializableTreeNodePublic;
  /** Income Data */
  income_data: DateAndBalancePublic[];
}

/** PermissionPublic */
export interface PermissionPublic {
  /** Admin */
  admin?: boolean | null;
  /** Pull */
  pull?: boolean | null;
  /** Push */
  push?: boolean | null;
}

/**
 * PlaintextJournalResponse
 * Response schema for plaintext journal.
 */
export interface PlaintextJournalResponse {
  /**
   * Content
   * Plaintext journal content
   */
  content: string;
}

/**
 * Posting
 * A Beancount posting.
 */
export interface Posting {
  /** Units of the posting */
  units: Amount;
  /** Cost of the posting */
  cost?: Cost | null;
  /**
   * Account
   * Account of the posting
   */
  account: string;
  /** Price of the posting */
  price?: Amount | null;
  /**
   * Meta
   * Metadata of the posting
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Flag
   * Flag of the posting
   */
  flag?: string | null;
}

/**
 * PostingPublic
 * Public schema for beancount posting.
 */
export interface PostingPublic {
  /** Account */
  account: string;
  /** Amount */
  amount: string;
  /** Commodity */
  commodity: string;
  /** Price */
  price?: string | null;
}

/**
 * PreReceiveCheckResponse
 * Response model for the pre-receive directive limit check
 */
export interface PreReceiveCheckResponse {
  /**
   * Allow
   * Whether the push should be accepted
   */
  allow: boolean;
  /**
   * Reason
   * Machine-readable reason code for the decision
   */
  reason: string;
  /**
   * New Directive Count
   * Directive count in the pushed tree
   */
  new_directive_count?: number | null;
  /**
   * Old Directive Count
   * Directive count currently on record, if known
   */
  old_directive_count?: number | null;
  /**
   * Limit
   * The tier's directive limit that was checked against
   */
  limit?: number | null;
}

/**
 * Price
 * A Beancount Price directive.
 */
export interface Price {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Currency
   * Currency for which this is a price
   */
  currency: string;
  /** Price amount */
  amount: Amount;
}

/**
 * PricePointPublic
 * A single price point with date and value.
 */
export interface PricePointPublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Value */
  value: string;
}

/**
 * QueryColumn
 * A query column definition.
 */
export interface QueryColumn {
  /**
   * Name
   * Name of the column
   */
  name: string;
  /**
   * Dtype
   * Data type of the column
   */
  dtype: string;
}

/**
 * QueryResult
 * Union of query result types.
 */
export interface QueryResult {
  /**
   * Result
   * The query result
   */
  result: QueryResultTable | QueryResultText;
}

/**
 * QueryResultTable
 * Table query result.
 */
export interface QueryResultTable {
  /**
   * Types
   * Column definitions
   */
  types: QueryColumn[];
  /**
   * Rows
   * Query result rows
   */
  rows: (string | number | boolean | null)[][];
  /**
   * T
   * Result type identifier
   * @default "table"
   */
  t?: string;
}

/**
 * QueryResultText
 * Text query result.
 */
export interface QueryResultText {
  /**
   * Contents
   * Text content of the query result
   */
  contents: string;
  /**
   * T
   * Result type identifier
   * @default "string"
   */
  t?: string;
}

/**
 * QueryTextResult
 * Plain text query result.
 */
export interface QueryTextResult {
  /**
   * Text
   * Formatted query output as plain text
   */
  text: string;
}

/** ReferencePublic */
export interface ReferencePublic {
  /** Ref */
  ref: string;
  object?: GitObjectPublic | null;
}

/** RenameUserRequest */
export interface RenameUserRequest {
  /** New Username */
  new_username: string;
}

/** RepoCommitPublic */
export interface RepoCommitPublic {
  /** Message */
  message: string;
}

/**
 * SerializableTreeNodePublic
 * A serializable tree node for account hierarchy.
 */
export interface SerializableTreeNodePublic {
  /** Account */
  account: string;
  /** Balance */
  balance: Record<string, string>;
  /** Balance Children */
  balance_children: Record<string, string>;
  /** Children */
  children: SerializableTreeNodePublic[];
  /** Has Txns */
  has_txns: boolean;
  /** Cost */
  cost?: Record<string, string> | null;
  /** Cost Children */
  cost_children?: Record<string, string> | null;
}

/** SuccessResponse[AccountJournalResponsePublic] */
export interface SuccessResponseAccountJournalResponsePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for account journal entries. */
  data: AccountJournalResponsePublic;
}

/** SuccessResponse[AccountReportPublic] */
export interface SuccessResponseAccountReportPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for account report. */
  data: AccountReportPublic;
}

/** SuccessResponse[AttributesPublic] */
export interface SuccessResponseAttributesPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for attributes. */
  data: AttributesPublic;
}

/** SuccessResponse[BalanceSheetDataPublic] */
export interface SuccessResponseBalanceSheetDataPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for balance sheet data for visualization. */
  data: BalanceSheetDataPublic;
}

/** SuccessResponse[BcioOptionsPublic] */
export interface SuccessResponseBcioOptionsPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for BcioOptions (beancount.io-specific options). */
  data: BcioOptionsPublic;
}

/** SuccessResponse[BeancountOptionsPublic] */
export interface SuccessResponseBeancountOptionsPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for BeancountOptions. */
  data: BeancountOptionsPublic;
}

/** SuccessResponse[ContextPublic] */
export interface SuccessResponseContextPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Context for an entry. */
  data: ContextPublic;
}

/** SuccessResponse[DeleteMultiSourceSlicesResponse] */
export interface SuccessResponseDeleteMultiSourceSlicesResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for deleting multiple source slices. */
  data: DeleteMultiSourceSlicesResponse;
}

/** SuccessResponse[DeleteSourceSliceResponse] */
export interface SuccessResponseDeleteSourceSliceResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for deleting a source slice. */
  data: DeleteSourceSliceResponse;
}

/** SuccessResponse[FavaOptionsPublic] */
export interface SuccessResponseFavaOptionsPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for FavaOptions. */
  data: FavaOptionsPublic;
}

/** SuccessResponse[HealthCheck] */
export interface SuccessResponseHealthCheck {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: HealthCheck;
}

/** SuccessResponse[IncomeStatementDataPublic] */
export interface SuccessResponseIncomeStatementDataPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for income statement data for visualization. */
  data: IncomeStatementDataPublic;
}

/** SuccessResponse[JournalQueryResponsePublic] */
export interface SuccessResponseJournalQueryResponsePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for exporting journal entries. */
  data: JournalQueryResponsePublic;
}

/** SuccessResponse[KeyPublic] */
export interface SuccessResponseKeyPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for key information (safe for API responses) */
  data: KeyPublic;
}

/** SuccessResponse[LedgerCollaboratorPermission] */
export interface SuccessResponseLedgerCollaboratorPermission {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: LedgerCollaboratorPermission;
}

/** SuccessResponse[LedgerFileContentPublic] */
export interface SuccessResponseLedgerFileContentPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: LedgerFileContentPublic;
}

/** SuccessResponse[LedgerPublic] */
export interface SuccessResponseLedgerPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: LedgerPublic;
}

/** SuccessResponse[LedgerSearchResults] */
export interface SuccessResponseLedgerSearchResults {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Search results for ledgers */
  data: LedgerSearchResults;
}

/** SuccessResponse[NoneType] */
export interface SuccessResponseNoneType {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: null;
}

/** SuccessResponse[OverviewPublic] */
export interface SuccessResponseOverviewPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for overview endpoint. */
  data: OverviewPublic;
}

/** SuccessResponse[PlaintextJournalResponse] */
export interface SuccessResponsePlaintextJournalResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for plaintext journal. */
  data: PlaintextJournalResponse;
}

/** SuccessResponse[PreReceiveCheckResponse] */
export interface SuccessResponsePreReceiveCheckResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response model for the pre-receive directive limit check */
  data: PreReceiveCheckResponse;
}

/** SuccessResponse[QueryResult] */
export interface SuccessResponseQueryResult {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Union of query result types. */
  data: QueryResult;
}

/** SuccessResponse[QueryTextResult] */
export interface SuccessResponseQueryTextResult {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Plain text query result. */
  data: QueryTextResult;
}

/** SuccessResponse[SerializableTreeNodePublic] */
export interface SuccessResponseSerializableTreeNodePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** A serializable tree node for account hierarchy. */
  data: SerializableTreeNodePublic;
}

/** SuccessResponse[TokenCreateResponse] */
export interface SuccessResponseTokenCreateResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for token creation (may include the actual token if returned by API) */
  data: TokenCreateResponse;
}

/** SuccessResponse[TrialBalanceDataPublic] */
export interface SuccessResponseTrialBalanceDataPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Public schema for trial balance data for visualization. */
  data: TrialBalanceDataPublic;
}

/** SuccessResponse[Union[LedgerFileContentPublic, NoneType]] */
export interface SuccessResponseUnionLedgerFileContentPublicNoneType {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: LedgerFileContentPublic | null;
}

/** SuccessResponse[Union[TransactionPublic, NoneType]] */
export interface SuccessResponseUnionTransactionPublicNoneType {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: TransactionPublic | null;
}

/** SuccessResponse[UpdateSourceSliceResponse] */
export interface SuccessResponseUpdateSourceSliceResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response schema for updating a source slice. */
  data: UpdateSourceSliceResponse;
}

/** SuccessResponse[UserPublic] */
export interface SuccessResponseUserPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  data: UserPublic;
}

/** SuccessResponse[WebhookGiteaResponse] */
export interface SuccessResponseWebhookGiteaResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response model for Gitea push webhook */
  data: WebhookGiteaResponse;
}

/** SuccessResponse[WebhookRepoCreateResponse] */
export interface SuccessResponseWebhookRepoCreateResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response model for repository creation webhook */
  data: WebhookRepoCreateResponse;
}

/** SuccessResponse[WebhookResponse] */
export interface SuccessResponseWebhookResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Response model for webhook data */
  data: WebhookResponse;
}

/** SuccessResponse[dict[str, AccountDataPublic]] */
export interface SuccessResponseDictStrAccountDataPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: Record<string, AccountDataPublic>;
}

/** SuccessResponse[list[AccountLastEntryPublic]] */
export interface SuccessResponseListAccountLastEntryPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: AccountLastEntryPublic[];
}

/** SuccessResponse[list[BeancountErrorPublic]] */
export interface SuccessResponseListBeancountErrorPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: BeancountErrorPublic[];
}

/** SuccessResponse[list[CommitPublic]] */
export interface SuccessResponseListCommitPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: CommitPublic[];
}

/** SuccessResponse[list[CommodityPairWithPricesPublic]] */
export interface SuccessResponseListCommodityPairWithPricesPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: CommodityPairWithPricesPublic[];
}

/** SuccessResponse[list[DateAndBalanceWithAccountBalancePublic]] */
export interface SuccessResponseListDateAndBalanceWithAccountBalancePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: DateAndBalanceWithAccountBalancePublic[];
}

/** SuccessResponse[list[DocumentPublic]] */
export interface SuccessResponseListDocumentPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: DocumentPublic[];
}

/** SuccessResponse[list[EntriesCountPerTypePublic]] */
export interface SuccessResponseListEntriesCountPerTypePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: EntriesCountPerTypePublic[];
}

/** SuccessResponse[list[EventPublic]] */
export interface SuccessResponseListEventPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: EventPublic[];
}

/** SuccessResponse[list[KeyPublic]] */
export interface SuccessResponseListKeyPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: KeyPublic[];
}

/** SuccessResponse[list[LedgerFileContentPublic]] */
export interface SuccessResponseListLedgerFileContentPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: LedgerFileContentPublic[];
}

/** SuccessResponse[list[LedgerPublic]] */
export interface SuccessResponseListLedgerPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: LedgerPublic[];
}

/** SuccessResponse[list[ReferencePublic]] */
export interface SuccessResponseListReferencePublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: ReferencePublic[];
}

/** SuccessResponse[list[TokenPublic]] */
export interface SuccessResponseListTokenPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: TokenPublic[];
}

/** SuccessResponse[list[UserPublic]] */
export interface SuccessResponseListUserPublic {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: UserPublic[];
}

/** SuccessResponse[list[WebhookResponse]] */
export interface SuccessResponseListWebhookResponse {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: WebhookResponse[];
}

/** SuccessResponse[list[dict]] */
export interface SuccessResponseListDict {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: Record<string, any>[];
}

/** SuccessResponse[list[str]] */
export interface SuccessResponseListStr {
  /**
   * Success
   * @default true
   */
  success?: boolean;
  /** Data */
  data: string[];
}

/**
 * TokenCreate
 * Schema for creating a new access token
 */
export interface TokenCreate {
  /**
   * Name
   * Name of the access token
   */
  name: string;
  /**
   * Scopes
   * List of scopes for the token.
   *         Valid values: all, read:activitypub, read:issue, write:misc, read:notification,
   *         read:organization, read:package, read:repository, read:user
   */
  scopes?:
    | (
        | "all"
        | "read:activitypub"
        | "read:issue"
        | "write:misc"
        | "read:notification"
        | "read:organization"
        | "read:package"
        | "read:repository"
        | "read:user"
      )[]
    | null;
}

/**
 * TokenCreateResponse
 * Response schema for token creation (may include the actual token if returned by API)
 */
export interface TokenCreateResponse {
  /** Id */
  id?: number | null;
  /** Name */
  name?: string | null;
  /** Scopes */
  scopes?:
    | (
        | "all"
        | "read:activitypub"
        | "read:issue"
        | "write:misc"
        | "read:notification"
        | "read:organization"
        | "read:package"
        | "read:repository"
        | "read:user"
      )[]
    | null;
  /** Sha1 */
  sha1?: string | null;
  /** Token Last Eight */
  token_last_eight?: string | null;
  /** Created At */
  created_at?: string | null;
  /** Last Used At */
  last_used_at?: string | null;
}

/**
 * TokenPublic
 * Public schema for access token information
 */
export interface TokenPublic {
  /** Id */
  id?: number | null;
  /** Name */
  name?: string | null;
  /** Scopes */
  scopes?:
    | (
        | "all"
        | "read:activitypub"
        | "read:issue"
        | "write:misc"
        | "read:notification"
        | "read:organization"
        | "read:package"
        | "read:repository"
        | "read:user"
      )[]
    | null;
  /** Sha1 */
  sha1?: string | null;
  /** Token Last Eight */
  token_last_eight?: string | null;
  /** Created At */
  created_at?: string | null;
  /** Last Used At */
  last_used_at?: string | null;
}

/**
 * Transaction
 * A Beancount Transaction directive.
 */
export interface Transaction {
  /**
   * Date
   * Date of the directive
   * @format date
   */
  date: string;
  /**
   * Meta
   * Metadata of the directive
   */
  meta?: Record<string, string | number | boolean | null> | null;
  /**
   * Flag
   * Flag of the transaction
   */
  flag: string;
  /**
   * Payee
   * Payee of the transaction
   */
  payee?: string | null;
  /**
   * Narration
   * Narration of the transaction
   */
  narration?: string | null;
  /**
   * Postings
   * Postings of the transaction
   */
  postings: Posting[];
  /**
   * Tags
   * Entry tags
   * @uniqueItems true
   */
  tags?: string[];
  /**
   * Links
   * Entry links
   * @uniqueItems true
   */
  links?: string[];
}

/**
 * TransactionPublic
 * Public schema for beancount transaction.
 */
export interface TransactionPublic {
  /**
   * Date
   * @format date
   */
  date: string;
  /** Payee */
  payee?: string | null;
  /** Narration */
  narration?: string | null;
  /** Postings */
  postings: PostingPublic[];
}

/**
 * TrialBalanceDataPublic
 * Public schema for trial balance data for visualization.
 */
export interface TrialBalanceDataPublic {
  /** A serializable tree node for account hierarchy. */
  income_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  liabilities_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  equity_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  expenses_hierarchy_data: SerializableTreeNodePublic;
  /** A serializable tree node for account hierarchy. */
  assets_hierarchy_data: SerializableTreeNodePublic;
}

/**
 * UpdateSourceSliceRequest
 * Request schema for updating a source slice.
 */
export interface UpdateSourceSliceRequest {
  /**
   * Entry Hash
   * Hash of the entry to update
   */
  entry_hash: string;
  /**
   * Sha256Sum
   * SHA256 hash of the current entry source for validation
   */
  sha256sum: string;
  /**
   * New Content
   * New content for the entry
   */
  new_content: string;
}

/**
 * UpdateSourceSliceResponse
 * Response schema for updating a source slice.
 */
export interface UpdateSourceSliceResponse {
  /**
   * Message
   * Success message
   */
  message: string;
  /**
   * Entry Hash
   * Hash of the updated entry
   */
  entry_hash: string;
  /**
   * New Sha256Sum
   * SHA256 hash of the updated entry source
   */
  new_sha256sum: string;
}

/**
 * UpdateWebhookRequest
 * Request model for updating a webhook
 */
export interface UpdateWebhookRequest {
  /**
   * Active
   * Whether the webhook is active
   */
  active?: boolean | null;
  /**
   * Authorization Header
   * Authorization header value
   */
  authorization_header?: string | null;
  /**
   * Branch Filter
   * Branch filter pattern
   */
  branch_filter?: string | null;
  /**
   * Config
   * Webhook configuration
   */
  config?: Record<string, string> | null;
  /**
   * Events
   * List of events to trigger webhook
   */
  events?: WebhookEvent[] | null;
}

/** UserPublic */
export interface UserPublic {
  /** Id */
  id?: number | null;
  /** Login */
  login?: string | null;
  /** Full Name */
  full_name?: string | null;
  /** Login Name */
  login_name?: string | null;
  /** Email */
  email?: string | null;
  /** Active */
  active?: boolean | null;
  /** Is Admin */
  is_admin?: boolean | null;
  /** Created */
  created?: string | null;
  /** Last Login */
  last_login?: string | null;
  /** Source Id */
  source_id?: number | null;
  /** Visibility */
  visibility?: string | null;
  /** Restricted */
  restricted?: boolean | null;
  /** Prohibit Login */
  prohibit_login?: boolean | null;
  /** Description */
  description?: string | null;
}

/**
 * WebhookGiteaRepo
 * Repository information from Gitea webhook (matches Gitea's Repository struct)
 */
export interface WebhookGiteaRepo {
  /**
   * Full Name
   * Full repository name (owner/repo)
   */
  full_name: string;
  /**
   * Name
   * Repository name
   */
  name: string;
  /** Repository owner */
  owner: WebhookGiteaRepoOwner;
}

/**
 * WebhookGiteaRepoOwner
 * Repository owner information from Gitea webhook
 */
export interface WebhookGiteaRepoOwner {
  /**
   * Username
   * Owner username
   */
  username: string;
}

/**
 * WebhookGiteaRequestParams
 * Request parameters for Gitea webhooks (push, repository, etc.)
 *
 * This matches Gitea's webhook payload structure used across different event types.
 * The repository field is consistent across push, repository.create, and other events.
 */
export interface WebhookGiteaRequestParams {
  /** Repository that triggered the webhook */
  repository: WebhookGiteaRepo;
  /** User who triggered the event */
  sender: WebhookGiteaSender;
  /**
   * Action
   * Action that triggered the webhook
   */
  action?: string | null;
}

/**
 * WebhookGiteaResponse
 * Response model for Gitea push webhook
 */
export interface WebhookGiteaResponse {
  /**
   * Status
   * Status of the webhook processing
   */
  status: string;
  /**
   * Repository
   * Full name of the repository
   */
  repository: string;
  /**
   * Timestamp
   * ISO timestamp of when the webhook was processed
   */
  timestamp: string;
  /**
   * Message
   * Human-readable message about the action taken
   */
  message: string;
}

/**
 * WebhookGiteaSender
 * Sender/User information from Gitea webhook
 */
export interface WebhookGiteaSender {
  /**
   * Username
   * Username of the user who triggered the event
   */
  username: string;
}

/**
 * WebhookRepoCreateResponse
 * Response model for repository creation webhook
 */
export interface WebhookRepoCreateResponse {
  /**
   * Status
   * Status of the webhook processing
   */
  status: string;
  /**
   * Repository
   * Full name of the repository
   */
  repository: string;
  /**
   * Hooks Installed
   * List of hooks that were installed
   */
  hooks_installed: string[];
  /**
   * Timestamp
   * ISO timestamp of when the webhook was processed
   */
  timestamp: string;
  /**
   * Message
   * Human-readable message about the action taken
   */
  message: string;
}

/**
 * WebhookResponse
 * Response model for webhook data
 */
export interface WebhookResponse {
  /**
   * Id
   * Webhook ID
   */
  id?: number | null;
  /** Webhook type */
  type?: WebhookType | null;
  /**
   * Active
   * Whether the webhook is active
   */
  active?: boolean | null;
  /**
   * Authorization Header
   * Authorization header value
   */
  authorization_header?: string | null;
  /**
   * Branch Filter
   * Branch filter pattern
   */
  branch_filter?: string | null;
  /**
   * Config
   * Webhook configuration
   */
  config?: Record<string, string> | null;
  /**
   * Events
   * List of events
   */
  events?: WebhookEvent[] | null;
  /**
   * Created At
   * Creation timestamp
   */
  created_at?: string | null;
  /**
   * Updated At
   * Last update timestamp
   */
  updated_at?: string | null;
}
